apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql
    imagePullPolicy: IfNotPresent
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - nodePort: 32002
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  type: NodePort

